### ISSUE TITLE
Socket status 200

### ISSUE THREAD

**Issue by kevinzhangftw** [jyleong/voiceminder-server#17]
to reproduce error:
run:
python3 src/run.py
lt -s voiceminder -p 5000
vim echo_client.py
~change to websocket.create_connection("ws://voiceminder.localtunnel.me")~
python3 echo_client.py

on client's side, error shown:
--- request header ---
GET / HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: voiceminder.localtunnel.me
Origin: http://voiceminder.localtunnel.me
Sec-WebSocket-Key: 56Z81kA/Uw6oy92EUTDJSQ==
Sec-WebSocket-Version: 13

-----------------------
--- response header ---
HTTP/1.1 200 OK
Server: nginx/1.10.1

Date: Mon, 20 Nov 2017 14:31:15 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 13
Connection: keep-alive
-----------------------
Traceback (most recent call last):
  File "echo_client.py", line 6, in <module>
    ws = websocket.create_connection("ws://voiceminder.localtunnel.me")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/websocket/_core.py", line 487, in create_connection
    websock.connect(url, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/websocket/_core.py", line 214, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/websocket/_handshake.py", line 129, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d", status)
websocket._exceptions.WebSocketBadStatusException: Handshake status 200

**Comment by kevinzhangftw** [comment]
refer to wiki. run client using echoapp_client
